### ISSUE TITLE
Looking for paid help

### ISSUE THREAD

**Issue by DREW2212** [sergerdn/py-bas-automation#82]
@sergerdn very interesting script, I've been trying to do something similar for a few months and have been struggling. Can you contact me at https://t.me/buffalonian on telegram or live:c1b8f5d38c9e2b1e on skype?

**Comment by sergerdn** [comment]
Hello, @DREW2212.

Thank you for reaching out and sharing your interest. It's encouraging to hear that you're actively working on a similar project. 

If you need to incorporate my project into your scripts, I can offer a **free consultation** for you here.

I understand the complexities involved in such script and I am open to discussing how I can provide assistance. However, I would like to inform you that I do not offer private consultations through platforms like Telegram or Skype. 

For further communication, please provide your email address. I will reach out to you via email shortly to continue our discussion.

Looking forward to our collaboration.
